"""Recompute low-dim observations from flat MuJoCo sim states with the LOCAL
robosuite version, then rebuild train.npz + normalization.npz.

Why: the public robomimic hdf5 datasets store `object` observations generated by
robosuite 1.5.1, whose feature layout/conventions differ from robosuite 1.4.1
(the version this repo's eval envs use). Training on the stored obs while
evaluating on 1.4.1 obs silently corrupts the object features and yields ~0%
closed-loop success despite a healthy BC loss. Recomputing observations from the
flat `states` array via `env.reset_to()` with the local robosuite fixes the
semantics (verified to ~1e-8 against the live env).

Usage:
    python scripts/regen_observations.py --task can \
        --hdf5 /path/to/can_mh_low_dim_v15.hdf5 \
        --repo-root . --out-dir data/robomimic/can
"""
import argparse
import json
import os

import h5py
import numpy as np

TASK_SPEC = {
    "can": {
        "keys": ["robot0_eef_pos", "robot0_eef_quat", "robot0_gripper_qpos", "object"],
        "obs_dim": 23,
        "act_dim": 7,
    },
    "transport": {
        "keys": ["robot0_eef_pos", "robot0_eef_quat", "robot0_gripper_qpos",
                 "robot1_eef_pos", "robot1_eef_quat", "robot1_gripper_qpos", "object"],
        "obs_dim": 59,
        "act_dim": 14,
    },
}


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--task", choices=list(TASK_SPEC), default="can")
    p.add_argument("--hdf5", required=True, help="robomimic low_dim hdf5 (v15)")
    p.add_argument("--repo-root", default=".", help="repo root containing cfg/robomimic/env_meta/")
    p.add_argument("--out-dir", required=True, help="where to write train.npz / normalization.npz")
    args = p.parse_args()

    spec = TASK_SPEC[args.task]
    keys, obs_dim = spec["keys"], spec["obs_dim"]

    import robomimic.utils.env_utils as EnvUtils
    import robomimic.utils.obs_utils as ObsUtils

    ObsUtils.initialize_obs_modality_mapping_from_dict({"low_dim": keys})
    env_meta_path = os.path.join(args.repo_root, "cfg/robomimic/env_meta", f"{args.task}.json")
    env_meta = json.load(open(env_meta_path))
    env = EnvUtils.create_env_from_metadata(
        env_meta=env_meta, render=False, render_offscreen=False, use_image_obs=False
    )
    env.env.hard_reset = False
    env.reset()

    f = h5py.File(args.hdf5, "r")
    data = f["data"]
    demos = sorted(k for k in data.keys() if k.startswith("demo_"))
    S, A, R, D, L = [], [], [], [], []
    for i, dk in enumerate(demos):
        g = data[dk]
        states = g["states"][:]
        n = g.attrs["num_samples"]
        assert states.shape[0] == n
        L.append(n)
        A.append(g["actions"][:].astype(np.float32))
        R.append(g["rewards"][:].astype(np.float32))
        D.append(g["dones"][:].astype(np.int64))
        obs_seq = np.empty((n, obs_dim), dtype=np.float32)
        for t in range(n):
            raw = env.reset_to({"states": states[t]})
            obs_seq[t] = np.concatenate([np.asarray(raw[k]).flatten() for k in keys])
        S.append(obs_seq)
        if (i + 1) % 50 == 0:
            print(f"{i+1}/{len(demos)} demos done", flush=True)

    states = np.concatenate(S)
    actions = np.concatenate(A)
    rewards = np.concatenate(R)
    terminals = np.concatenate(D)
    traj_lengths = np.array(L)
    assert states.shape[0] == traj_lengths.sum() == actions.shape[0] == rewards.shape[0]

    obs_min, obs_max = states.min(0), states.max(0)
    action_min, action_max = actions.min(0), actions.max(0)
    states_n = 2 * (states - obs_min) / (obs_max - obs_min + 1e-6) - 1
    actions_n = 2 * (actions - action_min) / (action_max - action_min + 1e-6) - 1

    os.makedirs(args.out_dir, exist_ok=True)
    np.savez(os.path.join(args.out_dir, "normalization.npz"),
             obs_min=obs_min, obs_max=obs_max,
             action_min=action_min, action_max=action_max)
    np.savez(os.path.join(args.out_dir, "train.npz"),
             states=states_n.astype(np.float32), actions=actions_n.astype(np.float32),
             rewards=rewards, terminals=terminals, traj_lengths=traj_lengths)
    print("REBUILT", args.out_dir, "states", states.shape, "trajs", len(traj_lengths))


if __name__ == "__main__":
    main()
